from enum import Enum

class Banco(Enum):

    BANCOLOMBIA = ("BANCOLOMBIA", 0.0005, 1800)
    DAVIVIENDA =  ("DAVIVIENDA", 0.08, 2000)
    BBVA = ("BBVA", 0.005, 1500)
    BANCO_BOGOTA = ("BANCO_BOGOTA", 0.0001, 1600)
    BANCO_OCCIDENTE = ("BANCO_OCCIDENTE", 0.02, 2200)

    def __init__(self,NOMBRE, INTERES, COBRO_ADICIONAL):
        self.NOMBRE = NOMBRE
        self.INTERES = INTERES
        self.COBRO_ADICIONAL = COBRO_ADICIONAL
